export const START_RECTANGLE_DRAWING = 'START_RECTANGLE_DRAWING';
export const SAVE_RECTANGLE_DRAWING = 'SAVE_RECTANGLE_DRAWING';
export const CANCEL_RECTANGLE_DRAWING = 'CANCEL_RECTANGLE_DRAWING';
export const RECTANGLE_DRAWING_MODE_ON = 'ADD_NEW_LAYER';