export const TOGGLE_GRID_VISIBILITY = 'TOGGLE_GRID_VISIBILITY';
export const CHANGE_COLUMNS_AMOUNT = 'CHANGE_COLUMNS_AMOUNT';
export const CHANGE_COLUMNS_OFFSET = 'CHANGE_COLUMNS_OFFSET';
export const CHANGE_LEFT_PADDING = 'CHANGE_LEFT_PADDING';
export const CHANGE_RIGHT_PADDING = 'CHANGE_RIGHT_PADDING';
export const TOGGLE_SAME_PADDING = 'TOGGLE_SAME_PADDING';